### ISSUE TITLE
Please update npm

### ISSUE THREAD

**Issue by demian85** [wulkano/aperture#17]
I'm using github as dependency since npm has the same version but with different source code and method getAudioSources is missing.

Thanks.

**Comment by matheuss** [comment]
#8 needs to be fixed first 😅

**Comment by sindresorhus** [comment]
@matheuss I don't think that's necessary. None of those changes in #8 are breaking. I think we should just do a new release now.

**Comment by sindresorhus** [comment]
// @StefMa

**Comment by sindresorhus** [comment]
Done: https://github.com/wulkano/aperture/commit/0288c3b52e1a6cf5008c47faa2669882e1d22513 Note that we renamed this project from `aperture.js` to `aperture`.
