### ISSUE TITLE
Fix all the TODO's

### ISSUE THREAD

**Issue by sindresorhus** [wulkano/aperture#24]
In the JavaScript and Swift code.

**Comment by sindresorhus** [comment]
@matheuss This issue was for *actually fixing* what the TODO's say, not improving the TODO comments.

**Comment by matheuss** [comment]
😅 😅 😅 😅 😅 I misread it, my bad 😛

**Comment by CodeTheory** [comment]
At least there's more detail to them now 😆

**Comment by sindresorhus** [comment]
Looks like all the TODOs are fixed now.
