### ISSUE TITLE
Capture area in off-screen macOS space

### ISSUE THREAD

**Issue by mhkeller** [wulkano/Aperture#29]
I'm trying to find something that would capture an area in a "space" even if this space is not currently visible on any monitors. Is it possible to do this by setting an appropriate crop area? Happy to try and contribute some code if you have an idea on how this could be implemented.

**Comment by sindresorhus** [comment]
I doubt it's possible, but feel free to try.

Reference: https://github.com/mattr-/slate/issues/8

**Comment by sindresorhus** [comment]
Closing as it's not possible.
