### ISSUE TITLE
Internal Audio

### ISSUE THREAD

**Issue by legodude17** [wulkano/Aperture#31]
Would it be possible to record the internal audio (Sound effects, music, etc.)?

**Comment by matheuss** [comment]
Possible it is – but it's very hard 😕 There's no APIs for that – not even QuickTime supports it.

**Comment by legodude17** [comment]
Aww 😢  Well, it would be nice to have that.

**Comment by matheuss** [comment]
As far as I remember, we'd have to write a kernel extension for that 😅 Doable, bur definitely way beyond what we have time for at the moment 😔

**Comment by doot0** [comment]
I found this, which could potentially go some ways to making this a possibility but I fear that the added complexity could be a pain in the butt - https://github.com/ZECTBynmo/node-core-audio

**Comment by bhagyash007** [comment]
I just know swift but I really need  it. Also I wanna built it myself(no libraries), willing to learn audio kernels. Would be great if some one could point me in the right direction

**Comment by ldenoue** [comment]
The new ScreenCaptureKit API now allows us to capture audio from a given app/window:
https://developer.apple.com/documentation/screencapturekit/scstreamconfiguration/3955571-capturesaudio

Laurent
