### ISSUE TITLE
Ability to specify codec

### ISSUE THREAD

**Issue by jsejcksn** [wulkano/aperture#45]
[AVFoundation allows specifying the codec used in a recording](https://developer.apple.com/documentation/avfoundation/avvideocodectype). It would be very nice to support this in Aperture so that it can be included in Kap's settings.

**Comment by sindresorhus** [comment]
👍  I think we should also default to `hevc` if the user is running on High Sierra.

Pull request welcome when https://github.com/wulkano/aperture/pull/43 is merged.

**Comment by sindresorhus** [comment]
#43 was merged. Pull request welcome now :)
