### ISSUE TITLE
Possibly Add UVC Camera Device Recording?

### ISSUE THREAD

**Issue by chrisspiegl** [wulkano/Aperture#79]
The screen recording capabilities of this macOS implementation is incredibly impressive.

Would it be possible to add the ability to record Webcams as well with this method to be able to efficiently create "RAW" recordings of screen and webcam, in separate files, right from the CLI?

I am currently using `ffmpeg` for the webcam and `Aperture` for the screen, but would love to be able to use even less CPU for this.

Cheers.

**Comment by sindresorhus** [comment]
Recording webcam is already supported: https://github.com/wulkano/Aperture/commit/f6af76afa2f803778e4a76d1cd41ab413eaaded9

You can run multiple instances of Aperture at the same time.

**Comment by sindresorhus** [comment]
> Is this also available in the [aperture-node](https://github.com/wulkano/aperture-node) version?

It is not

**Comment by chrisspiegl** [comment]
Ok, then this ticket is done for no and we'll see on the ticket over at `aperture-node`:
https://github.com/wulkano/aperture-node/issues/25#issuecomment-1100216792
